version: '2'
services:
  web:
    image: org.kind-hack/volunteer_hub
    build:
      context: "."
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    container_name: sample_db
    image: postgres:9.5
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=volunteerhub
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
