CREATE TABLE PRINCIPAL (
    ID SERIAL PRIMARY KEY,
    USERNAME VARCHAR(100) UNIQUE NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    PASSWORD VARCHAR(100) NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    SURNAME VARCHAR(100) NOT NULL,
    PHOTO BYTEA,
    BIRTH_DATE DATE,
    ADDRESS VARCHAR(200)
);