CREATE TABLE ORGANISATION (
  ID SERIAL PRIMARY KEY,
  NAME VARCHAR(100) UNIQUE NOT NULL,
  DESCRIPTION VARCHAR(100) UNIQUE NOT NULL,
  PHOTO BYTEA,
  CREATION_DATE DATE
);

CREATE TABLE EVENT (
  ID SERIAL PRIMARY KEY,
  START_DATE DATE,
  END_DATE DATE,
  NAME VARCHAR(100) UNIQUE NOT NULL,
  DESCRIPTION VARCHAR(100) UNIQUE NOT NULL,
  MEMBER_REQUIREMENTS VARCHAR(100) UNIQUE NOT NULL,
  PHOTO BYTEA,
  CREATION_DATE DATE,
  ADDRESS VARCHAR(200),
  ORGANISATION_ID SERIAL,
  FOREIGN KEY (ORGANISATION_ID) REFERENCES ORGANISATION (id)
);

